swagger: "2.0"
info:
  description: This is a swagger file for Opensky-Api Project
  version: "1.0.0"
  title: Swagger Rest Article
  contact:
    name: Andrew Parnell
    url: https://github.com/parnelandr
    email: parnelandr@gmail.com
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /api

# Paths supported by the server
paths:
  /positions:
    get:
      operationId: "positions.read"
      tags:
        - "positions"
      summary: "Get the 10 most recent positions"
      description: "Get the 10 most recent positions from newest to oldest"
      responses:
        200:
          description: "Successful read positions operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                icao24:
                  type: "string"
                callsign:
                  type: "string"
                origin_country:
                  type: "string"
                time_position:
                  type: "integer"
                last_contact:
                  type: "integer"
                longitude:
                  type: "number"
                latiitude:
                  type: "number"
                baro_altiitude:
                  type: "number"
                on_ground:
                  type: "boolean"
                velocity:
                  type: "number"
                true_track:
                  type: "number"
                vertical_rate:
                  type: "number"
                sensors:
                  type: "string"
                geo_altitude:
                  type: "number"
                squawk:
                  type: "string"
                spi:
                  type: "boolean"
                postion_source:
                  type: "integer"

    post:
      operationId: positions.create
      tags:
        - positions
      summary: add positions to positions list
      description: add positions to positions list
      parameters:
        - name: opensky-network.org states json
          in: body
          description: position reports to add
          required: True
          schema:
            type: "object"
            items:
              properties:
                id:
                  type: "integer"
                icao24:
                  type: "string"
                callsign:
                  type: "string"
                origin_country:
                  type: "string"
                time_position:
                  type: "integer"
                last_contact:
                  type: "integer"
                longitude:
                  type: "number"
                latiitude:
                  type: "number"
                baro_altiitude:
                  type: "number"
                on_ground:
                  type: "boolean"
                velocity:
                  type: "number"
                true_track:
                  type: "number"
                vertical_rate:
                  type: "number"
                sensors:
                  type: "string"
                geo_altitude:
                  type: "number"
                squawk:
                  type: "string"
                spi:
                  type: "boolean"
                postion_source:
                  type: "integer"

      responses:
        201:
          description: Successfully added positions

